# Everything above is inherited from 'virtual' skeleton 

[project]
skeleton := "menhir"

[[package]]
skeleton = "driver"
dir = "src/!{name}"
name = "!{name}"

[package.dependencies]
!{name:alpha}_lib = "version"

[[package]]
skeleton = "menhir_lib"
dir = "src/!{name:alpha}_lib"
name = "!{name:alpha}_lib"
