[skeleton]
name = "wasm_binding"
inherits = "virtual"

[file]
dune_ = { file = "dune", skips = "@dune" }
"index.mld" = { skips = [ "@docs" ] }
"main.ml" = { skips = [ "@code" ] }
"main.c" = { skips = [ "@code" ] }
"main.h" = { skips = [ "@code" ] }
"stubs.c" = { skips = [ "@code" ] }
"stubs.js" = { skips = [ "@code" ] }
"wasm_utils.js" = { skips = [ "@code" ] }
"build_wasm.sh" = { skips = [ "@code" ] }
