# Everything above is inherited from 'virtual' skeleton 

[project]
skeleton := "ppx_deriver"

[[package]]
skeleton = "ppx_deriver"
dir = "src/!{name}"
kind = "library"
name = "!{name}"

[package.fields]
dune-stanzas = """
 ; add here in package.toml any runtime library of your ppx, 
 ; also add it to the [tools] section 
 (ppx_runtime_libraries )
"""
