# Everything above is inherited from 'virtual' skeleton 

[project]
skeleton := "ctypes_stubs"

[[package]]
skeleton = "ctypes_lib_stubs"
dir = "src/!{name:alpha}_lib"
gen-version = "version.ml"
kind = "library"
name = "!{name:alpha}"

[[package]]
skeleton = "ctypes_drv"
dir = "src/!{name}_prog"
kind = "program"
name = "!{name:alpha}_prog"
[package.dependencies]
!{name:alpha} = "version"
[package.fields]
lib-name = "!{name:alpha}"
