# Everything above is inherited from 'virtual' skeleton 

[project]
skeleton := "rust_binding"

[[package]]
skeleton = "rust_binding_lib"
dir = "src/!{name}"
name = "!{name}"

[[package]]
skeleton = "rust_binding_test"
dir = "src/!{name}_test"
kind = "program"
name = "!{name}_test"
[package.dependencies]
!{name} = "version"
