# Everything above is inherited from 'virtual' skeleton 

[project]
skeleton := "program"

[[package]]
skeleton = "driver"
dir = "src/!{name}"
kind = "program"
name = "!{name}"
[package.dependencies]
!{name:alpha}_lib = "version"

[[package]]
skeleton = "library"
dir = "src/!{name:alpha}_lib"
gen-version = "version.ml"
kind = "library"
name = "!{name:alpha}_lib"

