# Everything above is inherited from 'virtual' skeleton 

[project]
skeleton := "wasm_binding"

[dependencies]
bigstring = "0.3"

[[package]]
skeleton = "wasm_binding"
dir = "src/!{name}"
name = "!{name}"
