# Everything above is inherited from 'virtual' skeleton 

[project]
skeleton := "js_prg"
build-profile = "release"

[[package]]
skeleton = "js_driver"
dir = "src/!{name}"
name = "!{name}"

[[package]]
skeleton = "js_library"
dir = "src/!{name}_lib"
name = "!{name}_lib"
