# Everything above is inherited from 'virtual' skeleton 

[project]
skeleton := "vue"
build-profile = "release"

[[package]]
skeleton = "js_driver"
dir = "src/!{name:alpha}"
name = "!{name:alpha}"

[[package]]
skeleton = "vue_library"
dir = "src/!{name:alpha}_lib"
name = "!{name:alpha}_lib"
