[skeleton]
name = "menhir_lib"
inherits = "virtual"

[file]
"package.toml" = { create = true }
dune_ = { file = "dune", skips = "@dune" }
"index.mld" = { skips = [ "@docs" ] }
"main.ml" = { skips = [ "@code" ], create = true }
"lexer.mll" = { skips = [ "@code" ], create = true }
"parser.mly" = { skips = [ "@code" ], create = true }
"printer.ml" = { skips = [ "@code" ], create = true }
"types.ml" = { skips = [ "@code" ], create = true }
