# Everything above is inherited from 'virtual' skeleton 

[project]
skeleton := "library"

[[package]]
skeleton = "library"
dir = "src/!{name}"
gen-version = "version.ml"
kind = "library"
name = "!{name}"

