[skeleton]
name = "ctypes_lib_stubs"
inherits = "virtual"

[file]
"dune_" = { file = "dune", skips = [ "@dune" ] }
"index.mld" = { skips = [ "@docs" ] }
"lib.ml" = { file = "!{name}.ml", skips = [ "@code" ] }
"bindings/dune_" = { file = "bindings/dune", skips = [ "@dune" ] }
"bindings/gsl_functions_functor.ml" = { skips = [ "@code" ] }
"bindings/gsl_functions.ml" = { skips = [ "@code" ] }
"bindings/gen_functions.ml" = { skips = [ "@code" ] }
"bindings/gsl_types_functor.ml" = { skips = [ "@code" ] }
"bindings/gsl_types.ml" = { skips = [ "@code" ] }
"bindings/gen_types.ml" = { skips = [ "@code" ] }
"bindings/discover/dune_" = { file = "bindings/discover/dune", skips = [ "@dune" ] }
"bindings/discover/discover.ml" = { skips = [ "@code" ] }
"bindings/ctypes_stubgen/dune_" = { file = "bindings/ctypes_stubgen/dune", skips = [ "@dune" ] }
"bindings/ctypes_stubgen/ctypes_stubgen.ml" = { skips = [ "@code" ] }
"bindings/ctypes_stubgen/ctypes_stubgen.mli" = { skips = [ "@code" ] }
