# Everything above is inherited from 'virtual' skeleton 

[project]
skeleton := "mini_prg"
skip = "@test @sphinx @docs @ocamlformat @ocp-indent"

[[package]]
skeleton = "program"
dir = "src/!{name}"
name = "!{name}"

